### PR TITLE
updating/making doxygen compile again with minimal errors

### PR DESCRIPTION
**Pull request by l-hoang**
adding back snippets for manual, filling in missing param doxygens,
removing dead links, removing BigReducible, among other things

This makes doxygen compile again with minimal warnings.

### CODE REVIEW

**Comment by l-hoang** [comment]
clang-format failure was expected; I have some more changes coming down the pipeline soon.

**Comment by l-hoang** [comment]
Yes, it's probably likely that this will cause issues with the renaming project going on elsewhere. We'll need to check once that's done.

**Comment by l-hoang** [comment]
Will merge once CI finishes up just to make sure source code changes to get Doxygen working didn't break anything.

**Comment by nicelhc13** [comment]
I will restart all the works after merging everything that is going on!
(Thanks, Loc. You saved me yesterday :-))
So you can freely merge that.

**Pull request merged**
