### PR TITLE
Port Adaptive OBIM (PMOD) to Latest Galois

### PR DESCRIPTION
**Pull request by insertinterestingnamehere**
Fixes https://github.com/IntelligentSoftwareSystems/Galois/issues/78.

Very much still a work in progress. A relatively major overhaul is needed to get this up-to-date since the original PMOD scheduler was written against Galois 2.2.1 and so much has changed since then.

### CODE REVIEW

**Comment by insertinterestingnamehere** [comment]
Okay, I think the header for the new work list is ready to go. We need code that exercises it, so I'm planning on adding their implementation of A* search as well, but that can be done in a separate PR. Currently we're just testing that it compiles okay. Once we finalize this I'm planning on squashing all the commits since they're currently a bit of a mess.

**Comment by insertinterestingnamehere** [comment]
@bozhiyou FYI after looking through this code it appears that it actually still only handles integer priorities. For now to get floating point priorities we'll still have to do some sort of really conservative round-off scheme. I think their adaptive binning approach still can work with floats, but that'll take some more work beyond what's already here.

**Comment by insertinterestingnamehere** [comment]
With the exception of the changed parentheses in the last commit, this PR is not intended to significantly change the gehavior of the original adaptive OBIM scheduler. It's mainly focused at porting the original PMOD/Adaptive OBIM scheduler to the newer version of Galois. For reference, the original is available at  https://github.com/serifyesil/PMOD/blob/master/Galois-2.2.1/include/Galois/WorkList/AdaptiveObim.h.

**Comment by bozhiyou** [comment]
Thanks, Ian! I'm finalizing the code on my side and will check this out soon.

**Comment by insertinterestingnamehere** [comment]
@bozhiyou This is actually usable in apps now, though it'd definitely still benefit from a lot more testing. Please try it out and let me know if you run into any more bugs.

**Pull request merged**
