### PR TITLE
Clang format

### PR DESCRIPTION
**Pull request by ddn0**
clang-format used to run on the repo but it wasn't enforced. Since we have CI now, it should be easy to keep everything nice and clean going forward.

### CODE REVIEW

**Comment by insertinterestingnamehere** [comment]
Thus far I had avoided enforcing clang-format use since I'm not sure everyone knows how to run this locally yet. This is probably a good idea though. Does anyone else have any input?

**Comment by insertinterestingnamehere** [comment]
Rephrasing my comment slightly, I'm +1 on this, but I'd like to get buy-in from the rest of the group to avoid generating a lot of needless work.

**Comment by l-hoang** [comment]
+1

**Comment by roshandathathri** [comment]
+1

**Comment by ddn0** [comment]
It looks like there are slight differences in output between how clang-format-9 and clang-format-10. Do people have a preference as the one to enshrine in the CI (for now)?

**Comment by ddn0** [comment]
I also have a Dockerfile I can publish if folks have trouble installing clang-format.

**Comment by l-hoang** [comment]
clang-format is on our machines, so that's not a concern.

RE: clang version; no preference mostly because I don't know the differences.

**Comment by ddn0** [comment]
The support for this will come in with the merge from KatanaGraph. And the formatting itself should happen after all directory reorganization happens.

**Pull request closed without merging**
