### PR TITLE
Fixing LCI warnings

### PR DESCRIPTION
**Pull request by roshandathathri**

### CODE REVIEW

**Comment by roshandathathri** [comment]
> Needs a clang-format run

That's strange. I had run check-format on the files I changed.

**Comment by l-hoang** [comment]
clang-format on non-server machines (i.e. fusion, velocity, etc.) is a lower version than the one being used to cross check. I usually have to run on it on peltier, for instance.

**Comment by roshandathathri** [comment]
Thanks, Loc! Fixed it and pushed.

**Comment by l-hoang** [comment]
Something strange is going on with the arch build: been seeing that same error in other places as well.

Otherwise everything else passes so I'll just go ahead and merge it.

**Pull request merged**
