### PR TITLE
Move ktruss out of experimental

### PR DESCRIPTION
**Pull request by nicelhc13**
It is the first pull request for the further ktruss release tasks.

### CODE REVIEW

**Comment by nicelhc13** [comment]
I fetched from the release-5.0 branch but seems like conflicted. Let me check this issue..

**Comment by l-hoang** [comment]
Wait, we're using experimental ktruss?

I thought it was already in master?

**Comment by nicelhc13** [comment]
As I mentioned on the previous email, it seems like your modification was not reflected to the release-5.0 branch. and I fetched not master, but the release-5.0 branch. Should I fetch from the master branch?

**Comment by l-hoang** [comment]
Yes; lonestar/ktruss was something we pulled out of experimental a few months ago.

**Comment by nicelhc13** [comment]
OK. I reported this issue to Ian and will re-fetch it from the master branch. Thank you Loc.

**Comment by insertinterestingnamehere** [comment]
Clarifying here too: Release 5.0 is not the branch to use. That's last year's release. We haven't branched 6.0 yet. Master is the working copy.

**Comment by insertinterestingnamehere** [comment]
I'll defer to @l-hoang on which version to start from since he's more familiar with this particular app. I wasn't aware that there were two different versions in lonestar and experimental.

**Pull request closed without merging**
