### PR TITLE
Clean up stats

### PR DESCRIPTION
**Pull request by ddn0**

### CODE REVIEW

**Comment by ddn0** [comment]
Closes #121

**Comment by ddn0** [comment]
@insertinterestingnamehere The paths in lonestar-cpu-inputs.tar.gz seem to have changed, which is causing all the tests to fail.

You probably should do something like `tar -czf inputs.tar.gz --owner root --group root -C /net/path .` to keep the paths relative.

# Before

```
ddn@spork:katana-build$ tar tvzf inputs.2/lonestar-cpu-inputs.tar.gz | head -10
drwxr-xr-x ian/cam           0 2019-05-17 14:57 small_inputs/
drwxr-xr-x ian/cam           0 2019-05-17 14:53 small_inputs/scalefree/
drwxr-xr-x ian/cam           0 2019-05-17 14:55 small_inputs/scalefree/transpose/
-rw-r-xr-- ian/cam      139296 2019-03-28 12:34 small_inputs/scalefree/transpose/rmat10.tgr
-rw-r-xr-- ian/cam     4456480 2019-05-01 11:43 small_inputs/scalefree/transpose/rmat15.tgr
drwxr-xr-x ian/cam           0 2019-05-17 14:54 small_inputs/scalefree/symmetric/
-rw-r-xr-- ian/cam      262784 2019-03-28 12:35 small_inputs/scalefree/symmetric/rmat10.sgr
-rw-r-xr-- ian/cam     8609756 2019-05-01 11:43 small_inputs/scalefree/symmetric/rmat15.sgr
-rw-r-xr-- ian/cam      139296 2019-03-28 12:33 small_inputs/scalefree/rmat10.gr
-rw-r--r-- ian/cam     4456480 2019-05-01 11:41 small_inputs/scalefree/rmat15.gr
```

# After
```
ddn@spork:katana-build$ tar tvzf inputs/lonestar-cpu-inputs.tar.gz | head -10
drwxr-sr-x ian/cdgc          0 2020-04-22 09:52 net/ohm/export/iss/inputs/small_inputs/
drwxr-sr-x ian/cdgc          0 2020-04-22 09:48 net/ohm/export/iss/inputs/small_inputs/scalefree/
drwxr-sr-x ian/cdgc          0 2020-04-22 09:48 net/ohm/export/iss/inputs/small_inputs/scalefree/transpose/
-rw-r-xr-- ian/cdgc     139296 2020-04-22 09:48 net/ohm/export/iss/inputs/small_inputs/scalefree/transpose/rmat10.tgr
-rw-r-xr-- ian/cdgc    4456480 2020-04-22 09:48 net/ohm/export/iss/inputs/small_inputs/scalefree/transpose/rmat15.tgr
drwxr-sr-x ian/cdgc          0 2020-04-22 09:48 net/ohm/export/iss/inputs/small_inputs/scalefree/symmetric/
-rw-r-xr-- ian/cdgc     262784 2020-04-22 09:48 net/ohm/export/iss/inputs/small_inputs/scalefree/symmetric/rmat10.sgr
-rw-r-xr-- ian/cdgc    8609756 2020-04-22 09:48 net/ohm/export/iss/inputs/small_inputs/scalefree/symmetric/rmat15.sgr
-rw-r-xr-- ian/cdgc     139296 2020-04-22 09:48 net/ohm/export/iss/inputs/small_inputs/scalefree/rmat10.gr
-rw-r--r-- ian/cdgc    4456480 2020-04-22 09:48 net/ohm/export/iss/inputs/small_inputs/scalefree/rmat15.gr
```

**Comment by insertinterestingnamehere** [comment]
Thanks for catching that. My mistake. Will Fix shortly.

**Comment by insertinterestingnamehere** [comment]
Fixed in master. The CircleCI builds don't test the merge by default though, so a rebase or merge from master may be needed.

**Pull request merged**
