### PR TITLE
Graph Grammar Based Mesh Refinement

### PR DESCRIPTION
**Pull request by insertinterestingnamehere**
This is pulled in almost verbatim from https://github.com/Podsiadlo/TerrainMeshGenerator. I wasn't able to pull in the git history precisely though because of some large input files that had been stored in git and multiple merges had taken place since the large files were added. We should be able to make the inputs they need available as downloads through the usual channels we use for other apps.

@Podsiadlo, there are still some test failures in the unit tests. What should we do? Also, where can I look to see what command line arguments your app expects? We normally use llvm's command line parsing functionality to make handling command line arguments easy but this app appears to be doing something else.

### CODE REVIEW

**Comment by insertinterestingnamehere** [comment]
Fixes https://github.com/IntelligentSoftwareSystems/Galois/issues/113.

**Comment by ddn0** [comment]
Re: https://github.com/IntelligentSoftwareSystems/Galois/pull/117/commits/30921810e18b13dbe1a063ea42275c071792f556

You can join me on my neverending quest to remove util as a name :D https://github.com/KatanaGraph/katana/issues/2

**Comment by insertinterestingnamehere** [comment]
Yep. It'd be nice to get rid of util entirely. That commit just addresses the fact that having headers that only differ in capitalization makes it impossible to even check out the code on a machine with a case-insensitive filesystem (i.e. Windows).

**Comment by Podsiadlo** [comment]
Hi! The code obviously needs some refactoring. I'm going to look at it next week.

**Comment by insertinterestingnamehere** [comment]
@Podsiadlo Sounds great. Thank you!

**Comment by insertinterestingnamehere** [comment]
@bozhiyou FYI: this includes the code for generating inputs for the FMM simulation. As I understand it, the generated inputs are all synthetic. I'll be fixing some warnings and making the tests run in CI for this, but I'm going to merge this as soon as all the non-cuda builds are passing to make it easier for you to start using it.

**Comment by insertinterestingnamehere** [comment]
See also: https://github.com/insertinterestingnamehere/Galois/pull/1

**Comment by bozhiyou** [comment]
@insertinterestingnamehere Thank you! Also I'm reorganizing current FMM code with the latest release and did rebase on `fmm` branch, so please don't update that until I'm done.

**Pull request merged**
