### PR TITLE
Bump to C++17 standard

### LINKED ISSUE #69: Barriers test crashes with recent versions of clang

### PR DESCRIPTION
**Pull request by ddn0**
Recently there have been issues with aligned structures but without
aligned allocations. This can create segfaults as a compiler might
generate code assuming a certain alignment (e.g., vmovaps) but the
allocator does not preserve the same alignment [1].

This really seems to be an issue with ::operator new pre-C++17 and the
most stable fix is to move to a newer standard.

[1] https://stackoverflow.com/questions/52000359

Closes #69

### CODE REVIEW

**Comment by insertinterestingnamehere** [comment]
I'm very much in favor of this, but input from others would be greatly appreciated. For older CMake versions we could just manually add `-std=c++17` or `-std=c++1z` to the compiler arguments.

**Comment by ddn0** [comment]
@insertinterestingnamehere who would be good to bring into the discussion?

If we go to C++17, I think bringing up CMake to be the first version that supports `set(CMAKE_CXX_STANDARD 17)` seems reasonable.

I believe CMake would add `-std=c++1z` for older compilers.

**Comment by insertinterestingnamehere** [comment]
@amberhassaan may have an opinion.

**Comment by insertinterestingnamehere** [comment]
The only snag with old CMake versions is that our lmod modules at UT for CMake only give us CMake 3.3 with our gcc 6 package. It's not hard to fix the modules instead. @roshandathathri this will affect you until we get a newer CMake with the older gcc. Any preference? I'm inclined to let it be broken for a few days till we can get a newer CMake package.

**Comment by insertinterestingnamehere** [comment]
Clarification: I think we should merge this and then deal with the CMake module issue.

**Comment by roshandathathri** [comment]
For our heterogeneous code, we need to support gcc and other compiler versions supported by recent CUDA releases. For CUDA 9/10, that is gcc 7.

**Comment by insertinterestingnamehere** [comment]
> For our heterogeneous code, we need to support gcc and other compiler versions supported by recent CUDA releases. For CUDA 9/10, that is gcc 7.

We won't be dropping any compilers with this. Just CMake versions older than 3.8.

**Comment by insertinterestingnamehere** [comment]
Superseded by https://github.com/IntelligentSoftwareSystems/Galois/pull/79.

**Pull request closed without merging**
