### PR TITLE
Prefix CMake Argument names with GALOIS

### PR DESCRIPTION
**Pull request by insertinterestingnamehere**
Fixes https://github.com/IntelligentSoftwareSystems/Galois/issues/204. After a quick review of the remaining issues I figured it'd be nice to get this one done for the release since it was an easy fix.

### CODE REVIEW

**Comment by roshandathathri** [comment]
Thanks, Ian. One minor nit - consistency between test threads and test GPUs. Either user "num" for both or drop for both?

**Comment by insertinterestingnamehere** [comment]
I kept it in the GPU case because it seemed slightly ambiguous and could be interpreted like the `CUDA_VISIBLE_DEVICES`, but we're not able to handle comma separated lists of device ids. For the CPU, threads are already not tied to specific cores, so we're clearly not talking about some sort of affinity and there isn't really ambiguity.

**Comment by insertinterestingnamehere** [comment]
I guess `GALOIS_NUM_TEST_THREADS` is fine though. Not a huge deal either way.

**Comment by insertinterestingnamehere** [comment]
Updated. It's `GALOIS_NUM_TEST_THREADS` now.

**Comment by roshandathathri** [comment]
Thanks, Ian!

**Pull request merged**
