### PR TITLE
Don't error on newly introduced warnings

### PR DESCRIPTION
**Pull request by insertinterestingnamehere**
This should give the app authors time to fix these issues while not leaving CI totally broken.

### CODE REVIEW

**Comment by insertinterestingnamehere** [comment]
@ddn0 the fixes for some of these weren't obvious to me, so I'm proposing we give @Breakinbad time fix them.

**Comment by ddn0** [comment]
I think I got them all: https://github.com/IntelligentSoftwareSystems/Galois/pull/103

**Comment by insertinterestingnamehere** [comment]
Great, then let's just go with that. Thanks!

**Comment by Breakinbad** [comment]
Oh man that was fast! I just started to fix :p

**Pull request closed without merging**
