### PR TITLE
Lonestar Directory Reorganization

### PR DESCRIPTION
**Pull request by insertinterestingnamehere**

### CODE REVIEW

**Comment by ddn0** [comment]
FWIW, it might be easier on the history to squash all these commits so we can ignore them en-masse (git-commit-ignore). I don't know if having commits on a per-app basis is that much more informative than "Reorganize directories to follow application areas" (or some such thing).

**Comment by insertinterestingnamehere** [comment]
Sure. I can squash things if that'd be preferred.

**Comment by insertinterestingnamehere** [comment]
Okay, this is ready to go. I'll merge it once the tests pass.

**Comment by insertinterestingnamehere** [comment]
Quick note: In this PR I've also gotten rid of a bunch of the experimental code. I left lonestar/experimental for now though since some people are still working on apps there and we need to give them time to migrate their development somewhere else.

**Pull request merged**
