### PR TITLE
Fix warnings in bipart app

### PR DESCRIPTION
**Pull request by ddn0**

### CODE REVIEW

**Comment by ddn0** [comment]
@Breakinbad can you take a look?

The only remaining CI breakages seem to be unrelated to this change:
- fedora repo is down
- macos tests timing out

**Comment by ddn0** [comment]
@insertinterestingnamehere I think https://github.com/IntelligentSoftwareSystems/Galois/pull/103/commits/83652791325981c0c668f04ea1f782f939600a46 is actually erroneous since `ww` is not actually used anywhere.

**Comment by insertinterestingnamehere** [comment]
Yep. That's my mistake. @Breakinbad, d4e561293b8d170978144c374697ed25d363e034 can't be fixing a bug. That variable isn't actually used anywhere. I'll figure out how to fix that merge.

**Comment by insertinterestingnamehere** [comment]
Actually @ddn0 beat me to it. Thanks!

**Pull request merged**
