### PR TITLE
fix issue 208: invalid argument

### PR DESCRIPTION
**Pull request by chenxuhao**
fix issue 208: Error when running applications in lonestar/mining

### CODE REVIEW

**Comment by insertinterestingnamehere** [comment]
Needs clang-format, but otherwise looks good to me.

**Comment by chenxuhao** [comment]
clang-format is done

**Comment by insertinterestingnamehere** [comment]
Thanks, the format build is still failing on `libpangolin/include/pangolin/BfsMining/vertex_miner.h`. Please run clang-format there as well.

**Comment by insertinterestingnamehere** [comment]
Build failures are unrelated. Merging.

**Pull request merged**
